### ISSUE TITLE
Making the http access logs debug logs

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/events#19]
@f2prateek 
@yields
@abraithwaite 

I feel like in every project where I've used this package I never wanted to have the access http access logs how up by default, which resulted in code that looked like this:
```go
if debug {
  handler = httpevents.NewHandler(handler)
}
```

What would you guys think about making the access logs debug logs by default?

**Comment by f2prateek** [comment]
So I actually have them enabled for the services I have it on - except for the /internal/health route.

I would definitely want to see 5xx appear as regular logs.

**Comment by achille-roussel** [comment]
Your point about 5xx is valid. Any downsides of having 5xx always enabled, then 1xx/2xx/3xx/4xx showing up as debug logs?

**Comment by achille-roussel** [comment]
@f2prateek 
@abraithwaite 

Are we good on making 1xx/2xx/3xx logs enabled in debug mode, 4xx/5xx enabled all the time?

**Comment by f2prateek** [comment]
👍 For my services I would be ok with that.

**Comment by f2prateek** [comment]
On more thinking, I think that totally makes sense as a default. It might be worth thinking about how people could opt out and log everything if they wanted to.

**Comment by achille-roussel** [comment]
One can always configure the access logs to use a logger that has debug enabled (even if the default logger doesn't).
